version: "3.5"

services:
  app:
    build: .
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - 80:80

  db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "book-directory"
    ports:
      - 5455:5432

  redis:
    image: redis:7.2.4-alpine
    restart: always
    environment:
      - REDIS_PORT=6379
    ports:
      - 6379:6379
