version: "3.5"

services:
  app:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - 80:80

  db:
    image: postgres:15.5
    restart: always
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "book-directory"
    ports:
      - 5455:5432
