
services:
  app:
    container_name: book-directory
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    command: bash -c "npm run migrate:up && npm run seed:up && npm run start:dev"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    ports:
      - 80:${APP_PORT}
    networks:
      - db_network
      - cache_network

  db:
    container_name: book-directory-db
    image: postgres:15.5
    restart: always
    environment:
      PSQL_HOST: database
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - db_network

  redis:
    container_name: book-directory-redis
    image: redis:7.2.4-alpine
    restart: always
    environment:
      - REDIS_PORT=6379
    ports:
      - 6379:6379
    networks:
      - cache_network

networks:
  db_network:
  cache_network:
