module.exports = {
  ACCESS_TOKEN_COOKIE_NAME: 'ACCESS_COOKIE',
  REFRESH_TOKEN_COOKIE_NAME: 'AUTH_COOKIE',
  ACCESS_TOKEN_AGE:  60 * 60, // 1 hour
  REFRESH_TOKEN_AGE: 7 * 24 * 60 * 60, // 7 days
  AUTH_API_TAG: 'auth',
};
