const ERROR_TYPES = {
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USER_VALIDATION_ERROR: 'USER_VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
};

module.exports = {
  ERROR_TYPES,
};
