const MIN_LIMIT_LENGHT = 20;
const DEFAULT_LIMIT_LENGHT = MIN_LIMIT_LENGHT;
const NORMAL_GROUPING_NAME = "ASC";
const REVERSE_GROUPING_NAME = "DESC";
const ALL_GROUPING_NAME = [NORMAL_GROUPING_NAME, REVERSE_GROUPING_NAME];

module.exports = {
  MIN_LIMIT_LENGHT,
  DEFAULT_LIMIT_LENGHT,
  NORMAL_GROUPING_NAME,
  REVERSE_GROUPING_NAME,
  ALL_GROUPING_NAME,
  MAX_LIMIT_LENGHT: 50,
  DEFAULT_PAGE_LENGHT: 0,
};
