const MIN_LIMIT_NUMBER = 20;
const MAX_LIMIT_NUMBER = 50;
const DEFAULT_LIMIT_NUMBER = MIN_LIMIT_NUMBER;
const MIN_PAGE_NUMBER = 0;
const DEFAULT_PAGE_NUMBER = MIN_PAGE_NUMBER;
const NORMAL_GROUPING_NAME = "ASC";
const REVERSE_GROUPING_NAME = "DESC";
const ALL_GROUPING_NAME = [NORMAL_GROUPING_NAME, REVERSE_GROUPING_NAME];

module.exports = {
  MIN_LIMIT_NUMBER,
  MAX_LIMIT_NUMBER,
  DEFAULT_LIMIT_NUMBER,
  MIN_PAGE_NUMBER,
  DEFAULT_PAGE_NUMBER,
  NORMAL_GROUPING_NAME,
  REVERSE_GROUPING_NAME,
  ALL_GROUPING_NAME,
};
