const READ_PERMISSION_NAME = "read";
const CREATE_PERMISSION_NAME = "create";
const UPDATE_PERMISSION_NAME = "update";
const DELETE_PERMISSION_NAME = "delete";

module.exports = {
  READ_PERMISSION_NAME,
  CREATE_PERMISSION_NAME,
  UPDATE_PERMISSION_NAME,
  DELETE_PERMISSION_NAME,
};
