const USER_POLICY_NAME = "USER";
const ROLE_POLICY_NAME = "ROLE";
const POLICY_POLICY_NAME = "POLICY";
const BOOK_POLICY_NAME = "BOOK";

module.exports = {
  USER_POLICY_NAME,
  ROLE_POLICY_NAME,
  POLICY_POLICY_NAME,
  BOOK_POLICY_NAME,
};
